// <auto-generated />
using System;
using Danielle_Mathieu_Josia_Orevil_UA2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Danielle_Mathieu_Josia_Orevil_UA2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110052218_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Client", b =>
                {
                    b.Property<int>("idClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", b =>
                {
                    b.Property<int>("idCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientidClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("TEXT");

                    b.Property<int>("idClient")
                        .HasColumnType("INTEGER");

                    b.HasKey("idCommande");

                    b.HasIndex("ClientidClient");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.CommandeProduit", b =>
                {
                    b.Property<int>("idCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idProduit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("prixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("idCommande", "idProduit");

                    b.HasIndex("idProduit");

                    b.ToTable("CommandeProduits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Produit", b =>
                {
                    b.Property<int>("idProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("estDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomProduit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("prix")
                        .HasColumnType("TEXT");

                    b.Property<int>("quantiteStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("idProduit");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", b =>
                {
                    b.Property<int>("idRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("idRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idUser");

                    b.HasIndex("idRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Client", "Client")
                        .WithMany("commandes")
                        .HasForeignKey("ClientidClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.CommandeProduit", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", "Commandes")
                        .WithMany("CommandeProduits")
                        .HasForeignKey("idCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Produit", "Produits")
                        .WithMany("CommandeProduits")
                        .HasForeignKey("idProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commandes");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.User", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("idRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Client", b =>
                {
                    b.Navigation("commandes");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", b =>
                {
                    b.Navigation("CommandeProduits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Produit", b =>
                {
                    b.Navigation("CommandeProduits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
