// <auto-generated />
using System;
using Danielle_Mathieu_Josia_Orevil_UA2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Danielle_Mathieu_Josia_Orevil_UA2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101161620_initDB")]
    partial class initDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdClient");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientIdClient")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateCommande")
                        .HasColumnType("TEXT");

                    b.Property<int>("idClient")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCommande");

                    b.HasIndex("ClientIdClient");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.CommandeProduit", b =>
                {
                    b.Property<int>("IdCommande")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProduit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCommande", "IdProduit");

                    b.HasIndex("IdProduit");

                    b.ToTable("CommandeProduits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomProduit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Prix")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdProduit");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleIdRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tache")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdRole");

                    b.HasIndex("RoleIdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RolesIdRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.HasIndex("RolesIdRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Client", "Client")
                        .WithMany("commandes")
                        .HasForeignKey("ClientIdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.CommandeProduit", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", "Commandes")
                        .WithMany("CommandeProduits")
                        .HasForeignKey("IdCommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Produit", "Produits")
                        .WithMany("CommandeProduits")
                        .HasForeignKey("IdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commandes");

                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", null)
                        .WithMany("Roles")
                        .HasForeignKey("RoleIdRole");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.User", b =>
                {
                    b.HasOne("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesIdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Client", b =>
                {
                    b.Navigation("commandes");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Commande", b =>
                {
                    b.Navigation("CommandeProduits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Produit", b =>
                {
                    b.Navigation("CommandeProduits");
                });

            modelBuilder.Entity("Danielle_Mathieu_Josia_Orevil_UA2.Model.Role", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
